### ISSUE TITLE
Enregistrer une action

### ISSUE THREAD

**Issue by baudu69** [baudu69/ProjetProgReparti#16]

**Comment by brsantoine** [comment]
Problème de CamelCase quand on ajoute une action
![image](https://user-images.githubusercontent.com/50876934/174283946-a813de9e-0607-4137-bcba-68e9d956dc3c.png)

**Comment by baudu69** [comment]
c'est la bdd qui est niqué
sur le prochain push j'ai un truc qui règle tout

**Comment by baudu69** [comment]
ça va tout regénérer
